# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Button
email: hinal.shah20@nmims.edu.in
description: >- # this means to ignore newlines until "baseurl:"
  Have you ever wondered how messed up your life would be if you lose the button from your pants while you are in an event? We are so busy cribbing about cars and gadjets that we don't value little things that make a huge difference in our life. This blog will contain those 'button' like assignments done by a design student pursuing B.des in Humaninsing Technology at NMIMS, School of Design. So stay tuned for more posts related to Design and Technology! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hinal150198
github_username:  hinal150198
google_analytics: UA-115617284-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
